version: '3.9'
services:
  db:
    image: mysql:8.0.32
    container_name: db-pos-system
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=pos_system
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ['CMD', 'mysqladmin' ,'ping', '-h', 'db']
      timeout: 10s
      retries: 5
  backend:
    container_name: backend-pos-system
    build: .
    ports:
      - 3333:3333
    working_dir: /app-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=3333
      - HOST=0.0.0.0
      - NODE_ENV=development
      - APP_KEY=sKZfnAryROQaxZUKPBuEhmFHxplPWK3D
      - DRIVE_DISK=local
      - DB_CONNECTION=mysql
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DB_NAME=pos_system
    restart: 'always'
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:3001']
      timeout: 10s
      retries: 5
