version: '3.9'
services:
  db:
    image: mysql:8.0.32
    container_name: db-pos-system
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=pos_system
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
